"""added img columns

Revision ID: 3519da6d3506
Revises: ac34954a3d05
Create Date: 2023-12-12 17:37:37.755374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3519da6d3506'
down_revision = 'ac34954a3d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_img', sa.String(), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('book_img')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('author_img')

    # ### end Alembic commands ###
